"""Project-wide constants: PII entity mappings, dataset categories, topic lists,
attack technique combinations, dataset column schemas, and GLiNER filter values.
"""
PII_ENTITIES: dict = {  # mapping of analyzer to generator entities
    "CREDIT_CARD": "credit_card_number",
    "IBAN_CODE": "iban",
    "US_SSN": "ssn",
    "PHONE_NUMBER": "phone_number",
    "EMAIL_ADDRESS": "email",
}
LOOKALIKE_TYPES: list = [
    "SHA-256 hash",
    "MD5 hash",
    "UUID v4",
    "shipping tracking number",
    "order ID with digit and letter pattern",
    "invoice number",
    "MAC address",
    "IPv6 address",
    "git commit SHA",
    "build pipeline ID",
    "serial number",
    "ETag",
    "hex color or hex string",
]
LOWERCASE_OPENERS: list = [
    # first-person
    "i",
    "i need",
    "i want",
    "i'd like",
    "i was wondering",
    "i'm trying to",
    "im trying to",
    "im looking for",
    "im wondering",
    "im hoping to",
    "im not sure",
    "i need help with",
    "i want to know",
    "i cant figure out",
    # greetings / casual
    "hey",
    "hey can you",
    "hi",
    "yo",
    "omg",
    "ok so",
    "so",
    "wait",
    "actually",
    "btw",
    # short markers
    "quick question",
    "quick q",
    "tldr:",
    "lazy question:",
    "dumb question:",
    # questions / asks
    "wondering if",
    "any idea",
    "any tips for",
    "any way to",
    "is there a way to",
    "is it possible to",
    "can i",
    "could i",
    "how do i",
    "how can i",
    "why does",
    "whats up with",
    "whats the deal with",
    "what's the best",
    # asks
    "need help with",
    "looking for",
    "trying to",
    "thinking about",
    "got a question about",
    "remind me",
    "walk me through",
    # mood-led
    "frustrated with",
    "confused about",
    "excited about",
    "worried about",
    # after-the-fact
    "just got",
    "just bought",
    "just tried",
    "recently noticed",
    # explainers
    "explain how",
    "explain why",
]
TITLECASE_OPENERS: list = [
    # first-person
    "I",
    "I need",
    "I want",
    "I'm trying to",
    "I'm looking for",
    "I'm wondering",
    "I need help with",
    "I want to know",
    # questions
    "How do I",
    "How can I",
    "What's the best",
    "What's a good",
    "Why does",
    "Why is",
    "Can you",
    "Could you",
    "Would you",
    # asks
    "Help me",
    "Help me with",
    "Tell me",
    "Show me",
    "Give me",
    "Looking for",
    "Need help with",
    "Search for",
    "Find me",
    "Walk me through",
    "Remind me",
    "Got a question about",
    # comparison / contextual
    "Summarize the",
    "Explain how",
    "Explain why",
    # after-the-fact
    "Just bought",
    "Just got",
    "Just tried",
    "Recently noticed",
    # mood-led (less common but realistic)
    "Frustrated with",
    "Confused about",
    "Worried about",
]
SCENARIOS: list = [
    "first-time user trying to figure something out",
    "frustrated user after a bad experience",
    "comparing options before making a purchase",
    "post-purchase support / dispute / refund question",
    "researcher gathering info for a project or paper",
    "automating a personal workflow",
    "writing or editing content (blog, email, document)",
    "helping a friend or family member figure something out",
    "in-a-hurry quick question, minimal context",
    "deep-diving / curious about a concept",
    "small-business owner asking for advice",
    "developer debugging or learning a new tool",
    "student doing homework or studying",
    "traveler planning or troubleshooting a trip",
    "parent juggling kid-related logistics",
]
# Backwards-compatible flat list (used only for inspection/tests).
OPENERS: list = LOWERCASE_OPENERS + TITLECASE_OPENERS
TONES: list = [
    "short one-line question to the assistant",
    "casual help-seeking question",
    "longer detailed help request explaining context first",
    "polite clarification follow-up question",
    "brainstorming or ideation request",
    "summarize-this request that pastes data inline",
    "explain-it-to-me question",
    "venting or frustrated about something",
    "sharing a quick observation and asking for feedback",
    "asking for a recommendation",
]
# Length labels and weights — modeled on real chat prompt distributions
# (most prompts are short).
LENGTHS: list = [
    "1 sentence",
    "2-3 sentences only",
    "a single paragraph (4-8 sentences)",
    "2-3 short paragraphs",
]
LENGTH_WEIGHTS: list = [0.3, 0.65, 0.04, 0.01]
TOPICS: list = [
    "finance",
    "human resources",
    "daily usage",
    "engineering",
    "healthcare",
    "academia",
    "government",
    "entertainment",
    "sports",
    "technology",
    "business",
    "gaming",
    "advertisement",
    "social media",
    "marketing",
    "executive",
    "education",
    "travel",
    "food and recipes",
    "legal",
    "real estate",
    "personal productivity",
    "writing assistance",
    "translation",
    "research",
    "fitness and wellness",
    "parenting",
    "shopping",
    "customer service",
    "career",
    "investing",
    "automotive",
    "nonprofit",
    "music",
    "art and design",
    "science",
    "data analysis",
    "coding help",
    "devops",
    "cybersecurity",
    "machine learning",
    "product management",
    "logistics",
    "manufacturing",
    "retail",
    "hospitality",
    "insurance",
    "agriculture",
    "energy",
    "environment",
]
FUZZY_TECHNIQUES: list[list] = [
    ["char_to_word"],
    ["chunking"],
    ["emojify"],
    ["homoglyph"],
    ["invisible_chars"],
    ["separators"],
]
ADV_CONTENT_TECHNIQUES: list[list] = [
    ["supportive_context"],
    # ["supportive_context", "affix_redacted"],
    ["supportive_context", "affix_ignore_pii"],
    ["supportive_context", "affix_category_prime"],
    # ["supportive_context", "pi_critical_text"],  # CriticalDetection, unsampled
    # ["supportive_context", "pi_ceo_instruct"],
    ["supportive_context", "pi_category_prime"],
    ["supportive_context", "affix_redacted", "pi_ceo_instruct"],
    ["supportive_context", "affix_ignore_pii", "pi_few_shot_safe"],
    # ["supportive_context", "affix_ignore_pii", "pi_educational_framing"],
    ["supportive_context", "affix_category_prime", "pi_category_prime"],
    ["supportive_context", "pi_few_shot_safe"],
    ["supportive_context", "pi_hypothetical"],
    ["supportive_context", "pi_educational_framing"],
]
DATASET_COLS: list = [
    "uid",
    "input_id",
    "category",
    "attack_target",
    "llm_input",
    "pii_spans",
]
GLINER_INVALID_VALUES: list = [  # values that should not be detected by GLiNER
    "email",  # GLiNER is triggered every time email is mentioned
    "e-addy",  # Slang for email
]
