CREDIT_CARD_VARIATIONS = [
    "credit card",
    "credit card number",
    "credit card no",
    "credit card num",
    "cc",
    "cc number",
    "cc no",
    "cc num",
    "credit",
    "card number",
    "card no",
    "card num",
]
SSN_VARIATIONS = [
    "ssn",
    "social security number",
    "social security",
    "social number",
    "ss",
    "social",
    "ssn number",
    "ss number",
    "ssn no",
    "ss no",
]
IBAN_VARIATIONS = [
    "iban",
    "iban code",
    "iban number",
    "iban no",
    "international bank account number",
    "international bank account",
    "international bank number",
    "international bank no",
    "bank account number",
    "bank account",
    "bank number",
    "bank no",
]
PHONE_VARIATIONS = [
    "phone number",
    "phone",
    "mobile number",
    "mobile",
    "smartphone",
    "cellphone",
    "cell phone",
    "cell",
    "contact number",
    "contact no",
    "tel",
    "telephone",
    "tele number",
    "handphone",
    "mobile phone",
    "work phone",
    "home phone",
    "office phone",
    "personal phone",
]
EMAIL_VARIATIONS = [
    "email",
    "email address",
    "email id",
    "email no",
    "email no.",
    "email id.",
    "mail",
    "mail address",
    "mail id",
    "mail no",
    "mail no.",
    "mail id.",
]
NUMBER_EMOJI_MAP = {
    "0": "0️⃣",
    "1": "1️⃣",
    "2": "2️⃣",
    "3": "3️⃣",
    "4": "4️⃣",
    "5": "5️⃣",
    "6": "6️⃣",
    "7": "7️⃣",
    "8": "8️⃣",
    "9": "9️⃣",
}
ALPHABET_EMOJI_MAP = {
    "a": "🅰",
    "b": "🅱",
    "c": "🅲",
    "d": "🅳",
    "e": "🅴",
    "f": "🅵",
    "g": "🅶",
    "h": "🅷",
    "i": "🅸",
    "j": "🅹",
    "k": "🅺",
    "l": "🅻",
    "m": "🅼",
    "n": "🅽",
    "o": "🅾",
    "p": "🅿",
    "q": "🆀",
    "r": "🆁",
    "s": "🆂",
    "t": "🆃",
    "u": "🆄",
    "v": "🆅",
    "w": "🆆",
    "x": "🆇",
    "y": "🆈",
    "z": "🆉",
}
PII_EMOJI_MAP = {
    "CREDIT_CARD": "💳",
    "SSN": "🪪",
    "BANK_ACCOUNT": "🏦",
    "PHONE_NUMBER": "📞",
    "EMAIL": "📧",
}
NUMBER_WORD_MAP = {
    "english": {
        "0": "zero",
        "1": "one",
        "2": "two",
        "3": "three",
        "4": "four",
        "5": "five",
        "6": "six",
        "7": "seven",
        "8": "eight",
        "9": "nine",
    },
    "spanish": {
        "0": "cero",
        "1": "uno",
        "2": "dos",
        "3": "tres",
        "4": "cuatro",
        "5": "cinco",
        "6": "seis",
        "7": "siete",
        "8": "ocho",
        "9": "nueve",
    },
    "french": {
        "0": "zéro",
        "1": "un",
        "2": "deux",
        "3": "trois",
        "4": "quatre",
        "5": "cinq",
        "6": "six",
        "7": "sept",
        "8": "huit",
        "9": "neuf",
    },
    "chinese": {
        "0": "零",
        "1": "一",
        "2": "二",
        "3": "三",
        "4": "四",
        "5": "五",
        "6": "六",
        "7": "七",
        "8": "八",
        "9": "九",
    },
    "hebrew": {
        "0": "אפס",
        "1": "אחד",
        "2": "שתיים",
        "3": "שלוש",
        "4": "ארבע",
        "5": "חמש",
        "6": "שש",
        "7": "שבע",
        "8": "שמונה",
        "9": "תשע",
    },
}
SEPARATORS = ["-", "_", ".", " ", "/", ":", ";", ","]
PARENTHESES = ["(", ")", "[", "]", "{", "}"]
