CREDIT_CARD_VARIATIONS = [
    "credit card",
    "credit card number",
    "credit card no",
    "credit card num",
    "cc",
    "cc number",
    "cc no",
    "cc num",
    "credit",
    "card number",
    "card no",
    "card num",
]
SSN_VARIATIONS = [
    "ssn",
    "social security number",
    "social security",
    "social number",
    "ss",
    "social",
    "ssn number",
    "ss number",
    "ssn no",
    "ss no",
]
IBAN_VARIATIONS = [
    "iban",
    "iban code",
    "iban number",
    "iban no",
    "international bank account number",
    "international bank account",
    "international bank number",
    "international bank no",
    "bank account number",
    "bank account",
    "bank number",
    "bank no",
]
PHONE_VARIATIONS = [
    "phone number",
    "phone",
    "mobile number",
    "mobile",
    "smartphone",
    "cellphone",
    "cell phone",
    "cell",
    "contact number",
    "contact no",
    "tel",
    "telephone",
    "tele number",
    "handphone",
    "mobile phone",
    "work phone",
    "home phone",
    "office phone",
    "personal phone",
]
EMAIL_VARIATIONS = [
    "email",
    "email address",
    "email id",
    "email no",
    "email no.",
    "email id.",
    "mail",
    "mail address",
    "mail id",
    "mail no",
    "mail no.",
    "mail id.",
]
NUMBER_EMOJI_MAP = {
    "0": "0️⃣",
    "1": "1️⃣",
    "2": "2️⃣",
    "3": "3️⃣",
    "4": "4️⃣",
    "5": "5️⃣",
    "6": "6️⃣",
    "7": "7️⃣",
    "8": "8️⃣",
    "9": "9️⃣",
}
ALPHABET_EMOJI_MAP = {
    "a": "🅰",
    "b": "🅱",
    "c": "🅲",
    "d": "🅳",
    "e": "🅴",
    "f": "🅵",
    "g": "🅶",
    "h": "🅷",
    "i": "🅸",
    "j": "🅹",
    "k": "🅺",
    "l": "🅻",
    "m": "🅼",
    "n": "🅽",
    "o": "🅾",
    "p": "🅿",
    "q": "🆀",
    "r": "🆁",
    "s": "🆂",
    "t": "🆃",
    "u": "🆄",
    "v": "🆅",
    "w": "🆆",
    "x": "🆇",
    "y": "🆈",
    "z": "🆉",
}
PII_EMOJI_MAP = {
    "CREDIT_CARD": "💳",
    "SSN": "🔒",
    "BANK_ACCOUNT": "🏦",
    "PHONE_NUMBER": "📞",
    "EMAIL": "📧",
}
