CREDIT_CARD_VARIATIONS = [
    "credit card",
    "credit card number",
    "credit card no",
    "credit card num",
    "cc",
    "cc number",
    "cc no",
    "cc num",
    "credit",
    "card number",
    "card no",
    "card num",
]
SSN_VARIATIONS = [
    "ssn",
    "social security number",
    "social security",
    "social number",
    "ss",
    "social",
    "ssn number",
    "ss number",
    "ssn no",
    "ss no",
]
IBAN_VARIATIONS = [
    "iban",
    "iban code",
    "iban number",
    "iban no",
    "international bank account number",
    "international bank account",
    "international bank number",
    "international bank no",
    "bank account number",
    "bank account",
    "bank number",
    "bank no",
]
PHONE_VARIATIONS = [
    "phone number",
    "phone",
    "mobile number",
    "mobile",
    "smartphone",
    "cellphone",
    "cell phone",
    "cell",
    "contact number",
    "contact no",
    "tel",
    "telephone",
    "tele number",
    "handphone",
    "mobile phone",
    "work phone",
    "home phone",
    "office phone",
    "personal phone",
]
EMAIL_VARIATIONS = [
    "email",
    "email address",
    "email id",
    "email no",
    "email no.",
    "email id.",
    "mail",
    "mail address",
    "mail id",
    "mail no",
    "mail no.",
    "mail id.",
]
